// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBie_07A5lO8vL4KvrAQzUFGE_eJs-bNGI',
    appId: '1:580880345563:web:8cb79bc47466b450a51ffe',
    messagingSenderId: '580880345563',
    projectId: 'mystore-demoapp',
    authDomain: 'mystore-demoapp.firebaseapp.com',
    storageBucket: 'mystore-demoapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2oHUWI9EcZINo5mwqjTLEH-gU3uJpbII',
    appId: '1:580880345563:android:e479de1f8bdefeb4a51ffe',
    messagingSenderId: '580880345563',
    projectId: 'mystore-demoapp',
    storageBucket: 'mystore-demoapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOARzpj_7LZJKyLxUK1LOwuXxe5lHEl9o',
    appId: '1:580880345563:ios:fd13bdec993c0e7da51ffe',
    messagingSenderId: '580880345563',
    projectId: 'mystore-demoapp',
    storageBucket: 'mystore-demoapp.appspot.com',
    iosClientId: '580880345563-csovbcj8mmdant9ll5dpanct7uqdanem.apps.googleusercontent.com',
    iosBundleId: 'com.example.mystore',
  );
}
